query CartInput($collectionIds: [ID!]) {
  presentmentCurrencyRate
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      deal: attribute(key: "_cartlift") {
        value
      }
      arm: attribute(key: "_cartlift_arm") {
        value
      }
      bar: attribute(key: "_cartlift_bar") {
        value
      }
      gift: attribute(key: "_cartlift_gift") {
        value
      }
      upsell: attribute(key: "_cartlift_upsell") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            inCollections(ids: $collectionIds) {
              collectionId
              isMember
            }
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app:cartlift", key: "config") {
      jsonValue
    }
  }
}
